### ISSUE TITLE
Name of the image without file extension

### ISSUE THREAD

**Issue by MacG-DD** [darickc/MMM-BackgroundSlideshow#106]
The name of the image also shows the file extension. 

Could you please remove it or use the title from the EXIF data?

**Comment by MacG-DD** [comment]
Add the function in the current version after line 634 or better above the line with

`imageProps.push(imageName);`

@darickc  Maybe someone can make a branch or master out of it. This is beyond my capabilities.

**Comment by cweinhofer** [comment]
Thanks @MacG-DD ! This was exactly what I was looking for, especially since [gpetersen/MMM-BackgroundSlideshowInfo](https://github.com/gpetersen/MMM-BackgroundSlideshowInfo) has stopped working for me.

I created the pull request to merge this into the main code.

PS - I changed the function name from `showNoFileExtension` to `imageInfoNoFileExt` just to better match the related config options.
