### ISSUE TITLE
Anyone gotten this to work with a cifs mount?

### ISSUE THREAD

**Issue by 1dollarbob** [darickc/MMM-BackgroundSlideshow#11]
I love the idea of this module, and it works great with a local directory.  I mounted a shared directory and pointed the imagePaths to the mount point, and all I get is a black background.  I've tried playing with permissions and paths, but haven't had any luck.  Any ideas on why this is happening or how to better debug?

**Comment by darickc** [comment]
I had this working with a file share, but it seemed to get disconnected a lot.  I now have it running in docker on my server and my Raspberry pi running in client only mode which is working great. 

Where are you defining your share at?  I believe it needs to be within the modules folder, otherwise the web server can't get to it.

**Comment by 1dollarbob** [comment]
I had it in ~/MagicMirror/media, once I moved it to ~/MagicMirror/modules/media it worked.

Thank you!
